AllCops:
  Exclude:
    - vendor/**

AlignParameters:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Max: 200
Metrics/ModuleLength:
  CountComments: false
  Max: 100
Metrics/BlockLength:
  CountComments: false
  Max: 100
StringLiterals:
  Enabled: false
