source 'https://rubygems.org'

gem 'berkshelf',  '~> 5.3'
gem 'chefspec',   '~> 5.3'
gem 'foodcritic', '~> 8.2'
gem 'rake',       '~> 12.0'
gem 'rubocop',    '~> 0.47'

group :plugins do
  gem 'vagrant-berkshelf', '~> 5.1'
  gem 'vagrant-omnibus',   '~> 1.5'
end

group :integration do
  gem 'kitchen-docker',  '~> 2.6'
  gem 'kitchen-vagrant', '~> 1.0'
  gem 'test-kitchen',    '~> 1.14'
end
