source 'https://rubygems.org'

gem 'chefspec',   '~> 5.3'
gem 'berkshelf',  '~> 5.3'
gem 'rake',       '~> 12.0'
gem 'rubocop',    '~> 0.47'
gem 'foodcritic', '~> 8.2'

group :plugins do
  gem "vagrant-berkshelf", '~> 5.1'
  gem "vagrant-omnibus",   '~> 1.5'
end

group :integration do
  gem 'test-kitchen',    '~> 1.14'
  gem 'kitchen-vagrant', '~> 0.21'
  gem 'kitchen-docker',  '~> 2.6'
end
